### ISSUE TITLE
Update SMADB_TLog_Backup.sql and change NOINIT to INIT

### ISSUE THREAD

**Issue by jesparzasma** [SMATechnologies/smautility-sql-scripts#4]
TLOG NOINIT continues to append to the file, the file can get quite large and cause issues in their environment.

Updating to INIT removing the NO does not append to the file and the file size is greatly reduced.

**Comment by hubgotter** [comment]
The following log backup command line in our SMA Database Backup job incorrectly has NOINIT instead of INIT. This causes the SMA Database Transaction Log Backup job's cumulative daily log backup to be retained and appended to when SMA Database Backup runs instead of removed and a new one created for the next day. The result is over time the transaction log backup becomes very large. Customer support cases have been open because the drive that has the transaction log backup fills.

BACKUP LOG [$(DatabaseName)] TO DISK = '$(PathToTranLogBackupFile)' WITH NOINIT
